/**
 * Admin › Certificates
 *   Tab 1: Certificate templates (participation / winner / jury / special)
 *   Tab 2: Issued certificates (generated by publishing results)
 */
import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery, queryOptions } from "@tanstack/react-query";
import { useState } from "react";
import { Plus, Pencil, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { DataTable } from "@/components/admin/DataTable";
import { ConfirmButton } from "@/components/admin/ConfirmButton";
import { EntityFormDialog, FieldRow } from "@/components/admin/EntityFormDialog";
import { useEntityCreate, useEntityUpdate, useEntityDelete } from "@/lib/adminCrud";
import { supabase } from "@/integrations/supabase/client";
import type { CertificateTemplate, Certificate } from "@/models/db";

const templatesQuery = queryOptions({
  queryKey: ["admin", "certificate-templates"],
  queryFn: async () => {
    const { data, error } = await supabase.from("certificate_templates").select("*").order("name");
    if (error) throw error;
    return (data ?? []) as CertificateTemplate[];
  },
});

type IssuedRow = Certificate & {
  events: { name: string } | null;
  teams: { name: string } | null;
  participants: { full_name: string; email: string } | null;
};
const issuedQuery = queryOptions({
  queryKey: ["admin", "certificates-issued"],
  queryFn: async () => {
    const { data, error } = await supabase
      .from("certificates")
      .select("*, events(name), teams(name), participants(full_name, email)")
      .order("issued_at", { ascending: false })
      .limit(500);
    if (error) throw error;
    return (data ?? []) as unknown as IssuedRow[];
  },
});

export const Route = createFileRoute("/admin/certificates")({
  loader: ({ context }) => {
    context.queryClient.ensureQueryData(templatesQuery);
    context.queryClient.ensureQueryData(issuedQuery);
  },
  component: CertificatesAdmin,
});

const TYPE_LABEL: Record<string, string> = {
  participation: "Participation",
  winner: "Winner",
  runner_up: "Runner Up",
  jury: "Jury",
  special: "Special",
};

function CertificatesAdmin() {
  const { data: templates } = useSuspenseQuery(templatesQuery);
  const { data: issued } = useSuspenseQuery(issuedQuery);
  const [dlg, setDlg] = useState<{ open: boolean; row?: CertificateTemplate }>({ open: false });

  const inv = [["admin", "certificate-templates"]];
  const create = useEntityCreate<CertificateTemplate>({ table: "certificate_templates", module: "certificates", invalidateKeys: inv });
  const update = useEntityUpdate<CertificateTemplate>({ table: "certificate_templates", module: "certificates", invalidateKeys: inv });
  const remove = useEntityDelete({ table: "certificate_templates", module: "certificates", invalidateKeys: inv });

  return (
    <div>
      <AdminPageHeader
        title="Certificates"
        description="Manage certificate templates and inspect certificates already issued by publishing results."
      />

      <Tabs defaultValue="templates" className="space-y-4">
        <TabsList>
          <TabsTrigger value="templates">Templates ({templates.length})</TabsTrigger>
          <TabsTrigger value="issued">Issued ({issued.length})</TabsTrigger>
        </TabsList>

        <TabsContent value="templates">
          <div className="mb-3 flex justify-end">
            <Button onClick={() => setDlg({ open: true })}>
              <Plus className="mr-1 h-4 w-4" /> New template
            </Button>
          </div>
          <DataTable
            rows={templates}
            searchFields={(r) => `${r.name} ${r.type ?? ""}`}
            columns={[
              { key: "name", header: "Name", render: (r) => <span className="font-medium">{r.name}</span> },
              { key: "type", header: "Type", render: (r) => TYPE_LABEL[r.type ?? "participation"] ?? r.type },
              {
                key: "bg",
                header: "Background",
                render: (r) =>
                  r.background_image_url ? (
                    <a href={r.background_image_url} target="_blank" rel="noreferrer" className="text-accent underline">
                      Open
                    </a>
                  ) : (
                    "—"
                  ),
              },
              { key: "status", header: "Status", render: (r) => r.status },
            ]}
            actions={(r) => (
              <>
                <Button size="sm" variant="outline" onClick={() => setDlg({ open: true, row: r })}>
                  <Pencil className="h-3.5 w-3.5" />
                </Button>
                <ConfirmButton onConfirm={() => remove.mutateAsync(r.id)} />
              </>
            )}
          />
        </TabsContent>

        <TabsContent value="issued">
          <DataTable
            rows={issued}
            searchFields={(r) =>
              `${r.certificate_code ?? ""} ${r.events?.name ?? ""} ${r.teams?.name ?? ""} ${r.participants?.full_name ?? ""} ${r.participants?.email ?? ""}`
            }
            columns={[
              {
                key: "code",
                header: "Code",
                render: (r) => <span className="font-mono text-xs">{r.certificate_code ?? "—"}</span>,
              },
              { key: "type", header: "Type", render: (r) => TYPE_LABEL[r.type] ?? r.type },
              { key: "event", header: "Event", render: (r) => r.events?.name ?? "—" },
              { key: "team", header: "Team", render: (r) => r.teams?.name ?? "—" },
              {
                key: "participant",
                header: "Participant",
                render: (r) => (
                  <div>
                    <div>{r.participants?.full_name ?? "—"}</div>
                    <div className="text-xs text-muted-foreground">{r.participants?.email ?? ""}</div>
                  </div>
                ),
              },
              { key: "issued_at", header: "Issued", render: (r) => new Date(r.issued_at).toLocaleString() },
              { key: "status", header: "Status", render: (r) => r.status },
            ]}
            actions={(r) =>
              r.certificate_code ? (
                <Button asChild size="sm" variant="outline">
                  <Link to="/certificate/$code" params={{ code: r.certificate_code }}>
                    <ExternalLink className="mr-1 h-3 w-3" /> View
                  </Link>
                </Button>
              ) : null
            }
          />
        </TabsContent>
      </Tabs>

      <EntityFormDialog<CertificateTemplate>
        open={dlg.open}
        onOpenChange={(v) => setDlg({ open: v })}
        title={dlg.row ? "Edit template" : "New template"}
        initial={
          dlg.row ??
          ({
            status: "active",
            type: "participation",
            fields: [] as unknown as CertificateTemplate["fields"],
          } as Partial<CertificateTemplate>)
        }
        onSubmit={async (values) => {
          if (dlg.row) await update.mutateAsync({ id: dlg.row.id, values });
          else await create.mutateAsync(values);
        }}
        render={({ values, setValue }) => (
          <>
            <FieldRow label="Name">
              <Input required value={(values.name as string) ?? ""} onChange={(e) => setValue("name", e.target.value)} />
            </FieldRow>
            <FieldRow label="Type">
              <select
                className="w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm"
                value={(values.type as string) ?? "participation"}
                onChange={(e) => setValue("type", e.target.value)}
              >
                {Object.entries(TYPE_LABEL).map(([k, v]) => (
                  <option key={k} value={k}>{v}</option>
                ))}
              </select>
            </FieldRow>
            <FieldRow label="Background image URL">
              <Input value={(values.background_image_url as string) ?? ""} onChange={(e) => setValue("background_image_url", e.target.value)} />
            </FieldRow>
            <FieldRow label="Logo URL">
              <Input value={(values.logo_url as string) ?? ""} onChange={(e) => setValue("logo_url", e.target.value)} />
            </FieldRow>
            <FieldRow label="Signature URL">
              <Input value={(values.signature_image_url as string) ?? ""} onChange={(e) => setValue("signature_image_url", e.target.value)} />
            </FieldRow>
            <FieldRow label="Fields (JSON)">
              <Textarea
                rows={5}
                className="font-mono text-xs"
                value={typeof values.fields === "string" ? values.fields : JSON.stringify(values.fields ?? [], null, 2)}
                onChange={(e) => {
                  try {
                    setValue("fields", JSON.parse(e.target.value) as unknown as CertificateTemplate["fields"]);
                  } catch {
                    setValue("fields", e.target.value as unknown as CertificateTemplate["fields"]);
                  }
                }}
              />
            </FieldRow>
            <FieldRow label="Status">
              <select
                className="w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm"
                value={(values.status as string) ?? "active"}
                onChange={(e) => setValue("status", e.target.value as CertificateTemplate["status"])}
              >
                <option value="active">active</option>
                <option value="inactive">inactive</option>
              </select>
            </FieldRow>
          </>
        )}
      />
    </div>
  );
}
