/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProblemStatementsRouteImport } from './routes/problem-statements'
import { Route as MyRegistrationRouteImport } from './routes/my-registration'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterSlugRouteImport } from './routes/register.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AdminTimelineRouteImport } from './routes/admin.timeline'
import { Route as AdminProblemStatementsRouteImport } from './routes/admin.problem-statements'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminContactMessagesRouteImport } from './routes/admin.contact-messages'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemStatementsRoute = ProblemStatementsRouteImport.update({
  id: '/problem-statements',
  path: '/problem-statements',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRegistrationRoute = MyRegistrationRouteImport.update({
  id: '/my-registration',
  path: '/my-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterSlugRoute = RegisterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegisterRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const AdminTimelineRoute = AdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemStatementsRoute = AdminProblemStatementsRouteImport.update({
  id: '/problem-statements',
  path: '/problem-statements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/contact-messages',
  path: '/contact-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/my-registration': typeof MyRegistrationRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRouteWithChildren
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/problem-statements': typeof AdminProblemStatementsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/my-registration': typeof MyRegistrationRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRouteWithChildren
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/problem-statements': typeof AdminProblemStatementsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/my-registration': typeof MyRegistrationRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRouteWithChildren
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/problem-statements': typeof AdminProblemStatementsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/my-registration'
    | '/problem-statements'
    | '/register'
    | '/results'
    | '/search'
    | '/sitemap.xml'
    | '/sponsors'
    | '/admin/audit-logs'
    | '/admin/contact-messages'
    | '/admin/departments'
    | '/admin/email-templates'
    | '/admin/gallery'
    | '/admin/problem-statements'
    | '/admin/timeline'
    | '/events/$slug'
    | '/register/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/my-registration'
    | '/problem-statements'
    | '/register'
    | '/results'
    | '/search'
    | '/sitemap.xml'
    | '/sponsors'
    | '/admin/audit-logs'
    | '/admin/contact-messages'
    | '/admin/departments'
    | '/admin/email-templates'
    | '/admin/gallery'
    | '/admin/problem-statements'
    | '/admin/timeline'
    | '/events/$slug'
    | '/register/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/my-registration'
    | '/problem-statements'
    | '/register'
    | '/results'
    | '/search'
    | '/sitemap.xml'
    | '/sponsors'
    | '/admin/audit-logs'
    | '/admin/contact-messages'
    | '/admin/departments'
    | '/admin/email-templates'
    | '/admin/gallery'
    | '/admin/problem-statements'
    | '/admin/timeline'
    | '/events/$slug'
    | '/register/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  MyRegistrationRoute: typeof MyRegistrationRoute
  ProblemStatementsRoute: typeof ProblemStatementsRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-statements': {
      id: '/problem-statements'
      path: '/problem-statements'
      fullPath: '/problem-statements'
      preLoaderRoute: typeof ProblemStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-registration': {
      id: '/my-registration'
      path: '/my-registration'
      fullPath: '/my-registration'
      preLoaderRoute: typeof MyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/$slug': {
      id: '/register/$slug'
      path: '/$slug'
      fullPath: '/register/$slug'
      preLoaderRoute: typeof RegisterSlugRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/timeline': {
      id: '/admin/timeline'
      path: '/timeline'
      fullPath: '/admin/timeline'
      preLoaderRoute: typeof AdminTimelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problem-statements': {
      id: '/admin/problem-statements'
      path: '/problem-statements'
      fullPath: '/admin/problem-statements'
      preLoaderRoute: typeof AdminProblemStatementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminProblemStatementsRoute: typeof AdminProblemStatementsRoute
  AdminTimelineRoute: typeof AdminTimelineRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminProblemStatementsRoute: AdminProblemStatementsRoute,
  AdminTimelineRoute: AdminTimelineRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface RegisterRouteChildren {
  RegisterSlugRoute: typeof RegisterSlugRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSlugRoute: RegisterSlugRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  MyRegistrationRoute: MyRegistrationRoute,
  ProblemStatementsRoute: ProblemStatementsRoute,
  RegisterRoute: RegisterRouteWithChildren,
  ResultsRoute: ResultsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
