/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProblemStatementsRouteImport } from './routes/problem-statements'
import { Route as MyRegistrationRouteImport } from './routes/my-registration'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyCertificateCodeRouteImport } from './routes/verify-certificate.$code'
import { Route as ScorecardCodeRouteImport } from './routes/scorecard.$code'
import { Route as RegisterSlugRouteImport } from './routes/register.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as AdminWinnersRouteImport } from './routes/admin.winners'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as AdminTimelineRouteImport } from './routes/admin.timeline'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScorecardsRouteImport } from './routes/admin.scorecards'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminProblemStatementsRouteImport } from './routes/admin.problem-statements'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEvaluationRouteImport } from './routes/admin.evaluation'
import { Route as AdminEmailTemplatesRouteImport } from './routes/admin.email-templates'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDbHealthRouteImport } from './routes/admin.db-health'
import { Route as AdminContactMessagesRouteImport } from './routes/admin.contact-messages'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemStatementsRoute = ProblemStatementsRouteImport.update({
  id: '/problem-statements',
  path: '/problem-statements',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRegistrationRoute = MyRegistrationRouteImport.update({
  id: '/my-registration',
  path: '/my-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyCertificateCodeRoute = VerifyCertificateCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => VerifyCertificateRoute,
} as any)
const ScorecardCodeRoute = ScorecardCodeRouteImport.update({
  id: '/scorecard/$code',
  path: '/scorecard/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSlugRoute = RegisterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegisterRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimelineRoute = AdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScorecardsRoute = AdminScorecardsRouteImport.update({
  id: '/scorecards',
  path: '/scorecards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemStatementsRoute = AdminProblemStatementsRouteImport.update({
  id: '/problem-statements',
  path: '/problem-statements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvaluationRoute = AdminEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailTemplatesRoute = AdminEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDbHealthRoute = AdminDbHealthRouteImport.update({
  id: '/db-health',
  path: '/db-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/contact-messages',
  path: '/contact-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/my-registration': typeof MyRegistrationRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRouteWithChildren
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/verify-certificate': typeof VerifyCertificateRouteWithChildren
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/db-health': typeof AdminDbHealthRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/problem-statements': typeof AdminProblemStatementsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/scorecards': typeof AdminScorecardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/scorecard/$code': typeof ScorecardCodeRoute
  '/verify-certificate/$code': typeof VerifyCertificateCodeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/my-registration': typeof MyRegistrationRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRouteWithChildren
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/verify-certificate': typeof VerifyCertificateRouteWithChildren
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/db-health': typeof AdminDbHealthRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/problem-statements': typeof AdminProblemStatementsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/scorecards': typeof AdminScorecardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/scorecard/$code': typeof ScorecardCodeRoute
  '/verify-certificate/$code': typeof VerifyCertificateCodeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/my-registration': typeof MyRegistrationRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRouteWithChildren
  '/results': typeof ResultsRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/verify-certificate': typeof VerifyCertificateRouteWithChildren
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/db-health': typeof AdminDbHealthRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/email-templates': typeof AdminEmailTemplatesRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/problem-statements': typeof AdminProblemStatementsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/scorecards': typeof AdminScorecardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/register/$slug': typeof RegisterSlugRoute
  '/scorecard/$code': typeof ScorecardCodeRoute
  '/verify-certificate/$code': typeof VerifyCertificateCodeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/downloads'
    | '/events'
    | '/gallery'
    | '/my-registration'
    | '/problem-statements'
    | '/register'
    | '/results'
    | '/search'
    | '/sitemap.xml'
    | '/sponsors'
    | '/verify-certificate'
    | '/winners'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/certificates'
    | '/admin/contact-messages'
    | '/admin/db-health'
    | '/admin/departments'
    | '/admin/email-templates'
    | '/admin/evaluation'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/notifications'
    | '/admin/problem-statements'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/scorecards'
    | '/admin/settings'
    | '/admin/timeline'
    | '/admin/website'
    | '/admin/winners'
    | '/certificate/$code'
    | '/events/$slug'
    | '/register/$slug'
    | '/scorecard/$code'
    | '/verify-certificate/$code'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/downloads'
    | '/events'
    | '/gallery'
    | '/my-registration'
    | '/problem-statements'
    | '/register'
    | '/results'
    | '/search'
    | '/sitemap.xml'
    | '/sponsors'
    | '/verify-certificate'
    | '/winners'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/certificates'
    | '/admin/contact-messages'
    | '/admin/db-health'
    | '/admin/departments'
    | '/admin/email-templates'
    | '/admin/evaluation'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/notifications'
    | '/admin/problem-statements'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/scorecards'
    | '/admin/settings'
    | '/admin/timeline'
    | '/admin/website'
    | '/admin/winners'
    | '/certificate/$code'
    | '/events/$slug'
    | '/register/$slug'
    | '/scorecard/$code'
    | '/verify-certificate/$code'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/downloads'
    | '/events'
    | '/gallery'
    | '/my-registration'
    | '/problem-statements'
    | '/register'
    | '/results'
    | '/search'
    | '/sitemap.xml'
    | '/sponsors'
    | '/verify-certificate'
    | '/winners'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/audit-logs'
    | '/admin/certificates'
    | '/admin/contact-messages'
    | '/admin/db-health'
    | '/admin/departments'
    | '/admin/email-templates'
    | '/admin/evaluation'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/notifications'
    | '/admin/problem-statements'
    | '/admin/registrations'
    | '/admin/reports'
    | '/admin/results'
    | '/admin/scorecards'
    | '/admin/settings'
    | '/admin/timeline'
    | '/admin/website'
    | '/admin/winners'
    | '/certificate/$code'
    | '/events/$slug'
    | '/register/$slug'
    | '/scorecard/$code'
    | '/verify-certificate/$code'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  MyRegistrationRoute: typeof MyRegistrationRoute
  ProblemStatementsRoute: typeof ProblemStatementsRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  VerifyCertificateRoute: typeof VerifyCertificateRouteWithChildren
  WinnersRoute: typeof WinnersRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  ScorecardCodeRoute: typeof ScorecardCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-statements': {
      id: '/problem-statements'
      path: '/problem-statements'
      fullPath: '/problem-statements'
      preLoaderRoute: typeof ProblemStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-registration': {
      id: '/my-registration'
      path: '/my-registration'
      fullPath: '/my-registration'
      preLoaderRoute: typeof MyRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify-certificate/$code': {
      id: '/verify-certificate/$code'
      path: '/$code'
      fullPath: '/verify-certificate/$code'
      preLoaderRoute: typeof VerifyCertificateCodeRouteImport
      parentRoute: typeof VerifyCertificateRoute
    }
    '/scorecard/$code': {
      id: '/scorecard/$code'
      path: '/scorecard/$code'
      fullPath: '/scorecard/$code'
      preLoaderRoute: typeof ScorecardCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$slug': {
      id: '/register/$slug'
      path: '/$slug'
      fullPath: '/register/$slug'
      preLoaderRoute: typeof RegisterSlugRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/winners': {
      id: '/admin/winners'
      path: '/winners'
      fullPath: '/admin/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timeline': {
      id: '/admin/timeline'
      path: '/timeline'
      fullPath: '/admin/timeline'
      preLoaderRoute: typeof AdminTimelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scorecards': {
      id: '/admin/scorecards'
      path: '/scorecards'
      fullPath: '/admin/scorecards'
      preLoaderRoute: typeof AdminScorecardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problem-statements': {
      id: '/admin/problem-statements'
      path: '/problem-statements'
      fullPath: '/admin/problem-statements'
      preLoaderRoute: typeof AdminProblemStatementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluation': {
      id: '/admin/evaluation'
      path: '/evaluation'
      fullPath: '/admin/evaluation'
      preLoaderRoute: typeof AdminEvaluationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-templates': {
      id: '/admin/email-templates'
      path: '/email-templates'
      fullPath: '/admin/email-templates'
      preLoaderRoute: typeof AdminEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/db-health': {
      id: '/admin/db-health'
      path: '/db-health'
      fullPath: '/admin/db-health'
      preLoaderRoute: typeof AdminDbHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminDbHealthRoute: typeof AdminDbHealthRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEmailTemplatesRoute: typeof AdminEmailTemplatesRoute
  AdminEvaluationRoute: typeof AdminEvaluationRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProblemStatementsRoute: typeof AdminProblemStatementsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminScorecardsRoute: typeof AdminScorecardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTimelineRoute: typeof AdminTimelineRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminWinnersRoute: typeof AdminWinnersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminDbHealthRoute: AdminDbHealthRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEmailTemplatesRoute: AdminEmailTemplatesRoute,
  AdminEvaluationRoute: AdminEvaluationRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProblemStatementsRoute: AdminProblemStatementsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminScorecardsRoute: AdminScorecardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTimelineRoute: AdminTimelineRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminWinnersRoute: AdminWinnersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface RegisterRouteChildren {
  RegisterSlugRoute: typeof RegisterSlugRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSlugRoute: RegisterSlugRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface VerifyCertificateRouteChildren {
  VerifyCertificateCodeRoute: typeof VerifyCertificateCodeRoute
}

const VerifyCertificateRouteChildren: VerifyCertificateRouteChildren = {
  VerifyCertificateCodeRoute: VerifyCertificateCodeRoute,
}

const VerifyCertificateRouteWithChildren =
  VerifyCertificateRoute._addFileChildren(VerifyCertificateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  MyRegistrationRoute: MyRegistrationRoute,
  ProblemStatementsRoute: ProblemStatementsRoute,
  RegisterRoute: RegisterRouteWithChildren,
  ResultsRoute: ResultsRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  VerifyCertificateRoute: VerifyCertificateRouteWithChildren,
  WinnersRoute: WinnersRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  ScorecardCodeRoute: ScorecardCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
